version: "3.9"
services:
  virtuoso:
    container_name: virtuoso
    environment:
      - DBA_PASSWORD=mysecret
    ports:
      - 1111:1111
      - 8890:8890
    volumes:
      - ./database:/database
    image: openlink/virtuoso-opensource-7:latest
  web:
    container_name: linkedweb
    volumes:
      - ./webserver:/webserver
    ports:
      - 80:5000
    image: lweb:latest
